### ISSUE TITLE
Customizable options

### ISSUE THREAD

**Issue by bellstrand** [bellstrand/totp-generator#1]
Add object with default properties and merge with input object:
- Epoch (default: Unix epoch)
- Interval (default: 30sec)
- Token Length (default: 6)
- Hash (default: SHA-1), which more are commonly used?, optional dependency?

**Comment by GreenanJay** [comment]
Is there also some support for why you cannot use Amazon's secret key system with the code?

**Comment by bellstrand** [comment]
@GreenanJay I'm not sure what your question is exactly.

**Comment by Encke** [comment]
https://github.com/Encke/totp-generator

I added some of those ... Ill add the token size now ... Good one!

**Comment by bellstrand** [comment]
@Encke I'll happily merge a pull-request from you once you're done! :)

**Comment by Encke** [comment]
Done!
