### ISSUE TITLE
TypeError: base32.replace is not a function

### ISSUE THREAD

**Issue by b1ek** [bellstrand/totp-generator#107]
After installing this library, i got this error

I tried removing node_modules and installing the project again, resetting the docker container but none of that helped, so i don't think its a problem on my end.
```
/opt/code/node_modules/totp-generator/index.js:42
        base32 = base32.replace(/=+$/, "")
                        ^
TypeError: base32.replace is not a function
    at base32tohex (/opt/code/node_modules/totp-generator/index.js:42:18)
    at getToken (/opt/code/node_modules/totp-generator/index.js:16:8)
    at User.getTotpCodes (/opt/code/models/user.js:16:33)
    at User.checkTotp (/opt/code/models/user.js:31:34)
    at User.authenticate (/opt/code/models/user.js:54:24)
    at async apiLogin (/opt/code/routes/admin.js:12:19)
```

My code:
```
const totp = require('totp-generator');

...

let codes = /* recovery codes */;
const period = (30 * 1000);

codes.push(parseInt(totp(totp, { timestamp: Date.now() - period}))); << exception
codes.push(parseInt(totp(totp)));
codes.push(parseInt(totp(totp, { timestamp: Date.now() + period})));
```

**Comment by bellstrand** [comment]
@b1ek `base32.replace(/=+$/, "")` is executed on the string you input as the first argument as in `totp("JBSWY3DPEHPK3PXP")`.
And looking at your code you're not inputing a string there, but the whole `totp` function with `totp(totp)`.

Try out my examples in the README.md and make sure the first argument is a string and I'm sure it will work!
