### ISSUE TITLE
Web Crypto API

### ISSUE THREAD

**Issue by 7heMech** [bellstrand/totp-generator#141]
Maybe you could replace jssha package with the [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) which is pretty much supported everywhere, and would be way faster since it's natively implemented by the runtimes.

**Comment by bellstrand** [comment]
@7heMech This is an issue tracker.
Feel free to open a PR if you'd like to contribute additional or improved functionality to this repository.

**Comment by bellstrand** [comment]
@7heMech Good question, It's not a deal-breaker for me personally. But let me check around some of the open-source repos using this to see which are heavily in use first!

I'm not against switching to bun per-se, but it would require replacing Dependabot as well.
So i'd rather wait for https://github.com/dependabot/dependabot-core/issues/6528 before making that switch :)

**Comment by bellstrand** [comment]
I looks like `SHA-1` AND `SHA-512` covers almost all cases I can find, so I'm all for it.
