### ISSUE TITLE
Occasionally produces a five digit TOTP

### ISSUE THREAD

**Issue by mixophrygian** [bellstrand/totp-generator#2]
when the otp substring results in a string that has zero as the first digit, parseInt will strip it off resulting in a five digit return value.

https://github.com/bellstrand/totp-generator/blob/master/index.js#L17

**Comment by bellstrand** [comment]
Cool, never noticed (we implemented a failover that retried our login sequence if it failed to fix a timing issue when generating a token right when the time slot swapped before we made the server check current and last token at authentication).

Anyhow, I'll make a fix and upload it asap.

**Comment by bellstrand** [comment]
Just a quick question, (the only way to do this is to return a string instead, (don't know why I ever parsed it to an integer).

This won't create a problem for you I hope?

**Comment by mixophrygian** [comment]
No in fact that's our desired type.  Thanks for the quick response!

**Comment by bellstrand** [comment]
fdc17811352ae74f2e23ec44d6747c39622c6ebd

**Comment by mixophrygian** [comment]
Thanks again

**Comment by bellstrand** [comment]
No problem, just give me a shout if you need anything else.

**Comment by benjaminbosko** [comment]
It's still an issue in caused by [the type definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/totp-generator/index.d.ts#L17) in TypeScript. Could you check it?

**Comment by bellstrand** [comment]
@benjaminbosko I can't do anything about the @DefinitelyTyped project, you have to send a PR to them to do anything about this.

**Comment by benjaminbosko** [comment]
Ok, thank you for the fast response!
