### ISSUE TITLE
Feature Request: Custom times/validation function

### ISSUE THREAD

**Issue by ncovercash** [bellstrand/totp-generator#20]
Heya,

I'd love some function that takes a secret and code as parameters and returns if the code is valid at the current time.  I'd really like if this had a `window` parameter as well that allowed ±1 intervals, ±2, etc. to be checked to account for the amount of time it takes a user to enter/submit their code.

If this isn't feasible or doesn't fit into your vision for the library, a parameter for an offset (or custom time altogether) would work nicely!

**Comment by bellstrand** [comment]
@ncovercash My vision was very narrow when I created this project 4 years ago, just solving the needs I had back then.
I'm coming back to this repo in the near future cause I'm soon gonna implement 2FA for my current project.

The biggest library that I can find today https://github.com/speakeasyjs/speakeasy haven't been updated for nearly 5 years now, so I think I'd be looking to extend this library with everything you need from generating tokens/secrets to verification. And probably implement support for hotp on top of that.

A window parameter would then be a superb idéa.

I'll probably change the naming of this library when that happens, and convert everything to TypeScript in that process.

If you have more thinks on your with list just give me a shout!

**Comment by ncovercash** [comment]
Honestly, my TOTP usage is fairly limited, just generation and verification (all that's done with JS is verification during setup, since the actual verification later is server side).  I'll let you know if I think of any more though!  Thanks for the great effort

**Comment by bellstrand** [comment]
After some evaluation I've decided to use https://github.com/yeojz/otplib rather then expanding functionality here.
So I'll close this PR since there are no plans on adding additional features.
