### ISSUE TITLE
Support more than 8-10 digits?

### ISSUE THREAD

**Issue by tgbv** [bellstrand/totp-generator#27]
No matter how many digits I set, it never returns beyond 8-10. Is there a way or an algorithm to support more digits?
```
const Totp = require('totp-generator')

console.log(
  Totp("JBSWY3DPEHPK3PXP", {
    digits: 48,
    period: 1,
  })
)
```

**Comment by bellstrand** [comment]
@tgbv I've not used this library for a couple of years now, so I have no good answer for you.
In my last project I've been using https://github.com/yeojz/otplib which I'd recommend instead of using my lib.
