### ISSUE TITLE
Amazon TOTP

### ISSUE THREAD

**Issue by GreenanJay** [bellstrand/totp-generator#4]
Hello, 

Im a Junior Developer and I ran into an issue where Amazon's token for TOTP will not work with this generator.

It took me some time however i've developed a working solution.

Would you be interested in said solution, explanation and code?

As this is my first contribution i'd like to get added to the list.

Thanks

**Comment by bellstrand** [comment]
Sorry for the slow reply, I've been out traveling for couple of weeks!
I would absolutely be interested in expanding the library to support Amazons tokens as well!

The contribution part can be solved! The repository does barely need any maintenance thou, it's been running smoothly without any major hiccups this far!
