### ISSUE TITLE
Input 9 digits to get the return value 0.

### ISSUE THREAD

**Issue by pumpkin-zbh** [bellstrand/totp-generator#45]
When I input 9 digits and the specified timestamp, I get a return value of 0.
```
const Totp = require('totp-generator')

console.log(
  Totp("3IS523AYRNFUE===", {
    digits: 9,
    timestamp: 1634193300000
  })
)
```

**Comment by pumpkin-zbh** [comment]
Thanks for your reply, I think I have found the reason. The 4 bytes intercepted by hmac are used for & calculation with ‘7fffffff'. This operation may make the final calculated otp value less than 9 digits. But even if the maximum length of otp value is not greater than 9 digits, I think all the final values should be returned.

**Comment by bellstrand** [comment]
@pumpkin-zbh I totally agree with that it should return all values (or throw an error).

**Comment by pumpkin-zbh** [comment]
No, I think the current approach is correct. It is consistent with the function library i use in the MCU.
