### ISSUE TITLE
Error: Cannot find module 'totp-generator' -> Even  I  installed it

### ISSUE THREAD

**Issue by stephenwang1011** [bellstrand/totp-generator#49]
![image](https://user-images.githubusercontent.com/3350356/140877356-e5700380-751b-4655-a4ee-0a8eb5d5645e.png)

**Comment by bellstrand** [comment]
@stephenwang1011 For NodeJS to find a package it needs to be installed locally inside the folders node_modules.
You just installed the package globally with the `-g` flag, remove it and everything should work.

**Comment by stephenwang1011** [comment]
thanks

**Comment by rayfoss** [comment]
otplib is also unmaintained... its still using node exclusive APIs like Buffer and Crypto, breaking browser support, deno, synode, etc. They also export a UMD browser bundle thats incompatible with ES Module builders and browser's module loader.

This seems better... but will require Node 16. If you are on typescript you may need to recast webcrypto as `as unknown as WebCrypto`
https://github.com/dpikalov/hotp-totp/blob/master/index.js
