### ISSUE TITLE
One time use custom setting

### ISSUE THREAD

**Issue by markhyng** [bellstrand/totp-generator#63]
How to avoid the totp can be reused many times within the period?

Can we have a custom setting for the totp use one time only? 

thanks

**Comment by bellstrand** [comment]
I'm sorry, I've got no clue what you're saying.
Please specify your problem and a potential solution if you have a real problem.

**Comment by arashifunsho** [comment]
I think what he's trying to ask is, how to ensure that a token is only used/verified ONCE within the epoch period, possibly without having to check against a database entry (if that's even possible)
