### ISSUE TITLE
rounding epoch off can lead to totp for next cycle

### ISSUE THREAD

**Issue by Codeiffor** [bellstrand/totp-generator#89]
https://github.com/bellstrand/totp-generator/blob/eafbb67a058077cc105874fb85f1a9d120ce193b/index.js#L17
Here in the last 500 ms of current 30 second cycle (or any other period) the totp will be calculated for the next cycle due to rounded off epoch, Shouldn't it be `Math.floor`?

**Comment by bellstrand** [comment]
@Codeiffor You're totally correct.
We should probably write some unit-test with a fake timer and correct this!

**Comment by Codeiffor** [comment]
https://github.com/bellstrand/totp-generator/pull/90

**Comment by bellstrand** [comment]
@Codeiffor Published as `v0.0.14`!
